### ISSUE TITLE
有发现在写入值，没有写入成功的情况吗

### ISSUE THREAD

**Issue by wangq2008** [iHomeSoft/OmronFinsTCP.Net#2]
使用这个组件，生产环境下，莫名有一两次写入值，没有写成功到PLC，返回的信息也是写入成功了，其实PLC里的值并没有修改

**Comment by iHomeSoft** [comment]
可能是地址值被覆盖了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangq2008 <notifications@github.com&gt;
发送时间: 2019年11月29日 12:00
收件人: iHomeSoft/OmronFinsTCP.Net <OmronFinsTCP.Net@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[iHomeSoft/OmronFinsTCP.Net] 有发现在写入值，没有写入成功的情况吗 (#2)




使用这个组件，生产环境下，莫名有一两次写入值，没有写成功到PLC，返回的信息也是写入成功了，其实PLC里的值并没有修改

**Comment by iHomeSoft** [comment]
1
